name: Run tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Use Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      - run: npm i
      - run: npm ci
      - run: cd example && npm i && cd ..
      - run: npm run lint
      - run: npm test
      - run: npx pkg-pr-new publish
